name: CI 
on:
  - push
  - pull_request

jobs: 
  test:
    runs-on: 'windows-2019'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go test -gcflags=all=-d=checkptr -v ./...
